"""
Generates a plain-text audit report from a pipeline result dict — the kind
a regulator or a cooperative's board might want to print/file/email.
Deliberately plain text, not a PDF: getting *a* report out is more valuable
this week than getting a beautifully typeset one; if you have time later,
pipe this string into the docx/pdf toolchain of your choice.
"""

from datetime import datetime

try:
    from ..utils.helpers import format_currency_npr
except ImportError:
    from utils.helpers import format_currency_npr


def generate_text_report(result: dict) -> str:
    lines = []
    lines.append("=" * 60)
    lines.append("TRUSTNET AI — COOPERATIVE HEALTH AUDIT REPORT")
    lines.append("=" * 60)
    lines.append(f"Cooperative: {result['cooperative_name']}")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"Data source: {result.get('scenario', 'unknown')}")
    lines.append("")
    lines.append(f"RISK SCORE: {result['score']}/100  ({result['band'].upper()})")
    lines.append("")

    if result.get("needs_manual_review"):
        lines.append("*** LOW-CONFIDENCE EXTRACTION — MANUAL REVIEW RECOMMENDED ***")
        lines.append("")

    lines.append("-" * 60)
    lines.append("FINDINGS")
    lines.append("-" * 60)
    if not result["flags"]:
        lines.append("No findings raised.")
    else:
        for i, flag in enumerate(result["flags"], 1):
            lines.append(f"{i}. [{flag['severity'].upper()}] {flag['explanation']}")
    lines.append("")

    lines.append("-" * 60)
    lines.append("LEDGER RATIOS")
    lines.append("-" * 60)
    for key, value in result["ratios"].items():
        label = key.replace("_", " ").title()
        if isinstance(value, (int, float)) and "total" in key:
            display = format_currency_npr(value)
        else:
            display = value
        lines.append(f"{label}: {display}")
    lines.append("")

    lines.append("-" * 60)
    lines.append("PLAIN-LANGUAGE EXPLANATION")
    lines.append("-" * 60)
    lines.append(result.get("ai_explanation", "—"))
    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by TrustNet AI — prototype, not a regulatory finding.")
    lines.append("=" * 60)

    return "\n".join(lines)


if __name__ == "__main__":
    sample_result = {
        "cooperative_name": "Samunnat Bikash Sahakari Sanstha",
        "scenario": "collapsing",
        "score": 0,
        "band": "high_risk",
        "flags": [
            {"severity": "critical", "explanation": "94.7% of all loan value has gone to related parties."},
        ],
        "ratios": {"total_loans_out": 2500000.0, "loan_to_deposit_ratio": 3.2},
        "ai_explanation": "This cooperative shows serious warning signs.",
    }
    print(generate_text_report(sample_result))
